import URI from '@theia/core/lib/common/uri'
import { FileService } from '@theia/filesystem/lib/browser/file-service'
import { inject, injectable } from '@theia/core/shared/inversify'
import { AGENT_DOCS_BUNDLE, AGENT_DOCS_DIR } from './agent-docs-bundle'
import { AGENTS_TEMPLATE } from './agents-template'

const INSTRUCTIONS_USER_SECTION_MARKER =
  '<!-- ROCKIT_MANAGED_SECTION_END: Users may add custom rules below this line. Do not modify lines above. -->'

@injectable()
export class AgentInstructionService {
  @inject(FileService) protected readonly fileService: FileService

  async ensureAgentFiles(directoryUri: URI, agentId: string): Promise<void> {
    const targetUri = this.normalizeInstructionTargetUri(directoryUri)
    await this.ensureAgentInstructionsFile(targetUri, agentId)
    await this.ensureManagedAgentDocsBundle(targetUri)
  }

  protected normalizeInstructionTargetUri(directoryUri: URI): URI {
    return directoryUri.path.base === AGENT_DOCS_DIR ? directoryUri.parent : directoryUri
  }

  protected async ensureAgentInstructionsFile(
    directoryUri: URI,
    agentId: string,
  ): Promise<void> {
    const fileName = agentId === 'claude' ? 'CLAUDE.md' : 'AGENTS.md'
    const instructionsUri = directoryUri.resolve(fileName)
    const managedTemplate = this.buildAgentInstructionsTemplate(agentId)
    if (!(await this.fileService.exists(instructionsUri))) {
      await this.fileService.create(instructionsUri, `${managedTemplate}\n`)
      return
    }
    const existing = await this.readTextFile(instructionsUri)
    const upgraded = this.upgradeAgentInstructions(existing, managedTemplate)
    if (upgraded !== existing) {
      await this.fileService.write(instructionsUri, upgraded)
    }
  }

  protected async ensureManagedAgentDocsBundle(directoryUri: URI): Promise<void> {
    const docsDirUri = directoryUri.resolve(`${AGENT_DOCS_DIR}/`)
    await this.fileService.createFolder(docsDirUri)

    for (const [fileName, content] of Object.entries(AGENT_DOCS_BUNDLE)) {
      const docUri = docsDirUri.resolve(fileName)
      const managedContent = `<!-- AUTO-GENERATED BY RocKIT. DO NOT EDIT THIS FILE DIRECTLY. -->\n\n${content.trimEnd()}\n`

      if (!(await this.fileService.exists(docUri))) {
        await this.fileService.create(docUri, managedContent)
        continue
      }

      const existing = await this.readTextFile(docUri)
      if (existing !== managedContent) {
        await this.fileService.write(docUri, managedContent)
      }
    }
  }

  protected buildAgentInstructionsTemplate(agentId: string): string {
    const heading = agentId === 'claude' ? '# CLAUDE.md' : '# AGENTS.md'
    const normalized = AGENTS_TEMPLATE.replace(/\r\n/g, '\n')
    const rewrittenHeading = normalized.replace(/^#\s+AGENTS\.md/m, heading)
    return rewrittenHeading.trimEnd()
  }

  protected upgradeAgentInstructions(
    existingContent: string,
    managedTemplate: string,
  ): string {
    const normalize = (value: string): string => value.replace(/\r\n/g, '\n').trim()
    const withLf = existingContent.replace(/\r\n/g, '\n')
    const marker = INSTRUCTIONS_USER_SECTION_MARKER
    const markerIndex = withLf.indexOf(marker)

    if (markerIndex >= 0) {
      const markerEnd = markerIndex + marker.length
      const managedPart = withLf.slice(0, markerEnd)
      const customPartRaw = withLf.slice(markerEnd).replace(/^\s*\n/, '')
      if (normalize(managedPart) === normalize(managedTemplate)) {
        return existingContent
      }
      const customPart = customPartRaw.trimEnd()
      return customPart.length > 0
        ? `${managedTemplate}\n\n${customPart}\n`
        : `${managedTemplate}\n`
    }

    const managedLegacy = managedTemplate.replace(`\n${marker}`, '')
    if (normalize(withLf) === normalize(managedLegacy)) {
      return `${managedTemplate}\n`
    }

    const preservedUserPart = withLf.trim()
    return preservedUserPart.length > 0
      ? `${managedTemplate}\n\n${preservedUserPart}\n`
      : `${managedTemplate}\n`
  }

  protected async readTextFile(uri: URI): Promise<string> {
    return (await this.fileService.read(uri)).value.toString()
  }
}
